print("****************** Python Practice ******************")
message="Pakistan Flag"
print(message)
print("*************************************")
print("*      *               ***          *")
print("*      *              *             *")
print("*      *             *              *")
print("*      *            *               *")
print("*      *           *        *       *")
print("*      *          *       *****     *")
print("*      *         *       *******    *")
print("*      *         *        *****     *")
print("*      *          *         *       *")
print("*      *           *                *")
print("*      *            *               *")
print("*      *             *              *")
print("*      *              *             *")
print("*      *               ***          *")
print("*************************************")

message="My Name Practice on Python"
print(message)
print("              *           *              *******   ")
print("             * *          *                 *      ")
print("            *   *         *                 *      ")
print("           *     *        *                 *      ")
print("          *       *       *                 *      ")
print("         ***********      *                 *      ")
print("        *           *     *                 *      ")
print("       *             *    *                 *      ")
print("      *               *   *                 *      ")
print("     *                 *  *************  *******   ")